### ISSUE TITLE
Possible github page to let use try the website?

### ISSUE THREAD

**Issue by Abstra208** [noobieyuh/Silly-Quotes#1]
If you go in the settings of this repo, you can see a pages section. In it you can enable pages for a branch, select main and share the given link on this repo and High Seas to give people an easier way to view your work.

**Comment by noobieyuh** [comment]
There's already a GitHub page up and running. I just didn't put the link up. It should be there now. Sorry about that!
![image](https://github.com/user-attachments/assets/7ad2cb49-0d23-4346-a5ec-c6bed8f4e96d)
